// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WheresWaldoApi.Data;

#nullable disable

namespace where_is_waldo_api_csharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605221726_UpdateCharacterModel")]
    partial class UpdateCharacterModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WheresWaldoApi.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<double>("TargetXRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetYRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("ToleranceXRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("ToleranceYRatio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ImageId", "CharacterType")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WheresWaldoApi.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageUrl")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WheresWaldoApi.Models.Character", b =>
                {
                    b.HasOne("WheresWaldoApi.Models.Image", "Image")
                        .WithMany("Characters")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("WheresWaldoApi.Models.Image", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
